name: bagaholicboy
favicon: null
layout_spectrum: 0.24252196680754423
typography_spectrum: 0.3566712874453515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.29635167121887207
  lightness: 0.13748603453859687
  saturation: 0.28554796427488327
  rhythmicContrast: 0.6690926549490541
purpose: []
